import { body, param } from 'express-validator';
import mongoose from 'mongoose';

export const productStoreValidator = [
    body('category_id').custom((value) => mongoose.Types.ObjectId.isValid(value)).withMessage('Valid category ID is required'),
    body('name_en').trim().notEmpty().withMessage('Name (EN) is required'),
    body('name_ar').trim().notEmpty().withMessage('Name (AR) is required'),
    body('slug').trim().notEmpty().withMessage('Slug is required'),
    body('description_en').optional().trim(),
    body('description_ar').optional().trim(),
    body('short_description_en').optional().trim(),
    body('short_description_ar').optional().trim(),
    body('image').optional().trim(),
    body('images').optional().isArray(),
    body('price').optional().isFloat({ min: 0 }),
    body('sku').optional().trim(),
    body('stock').optional().isInt({ min: 0 }),
    body('is_active').optional().isBoolean(),
    body('is_featured').optional().isBoolean(),
    body('order').optional().isInt(),
    body('meta_title_en').optional().trim(),
    body('meta_title_ar').optional().trim(),
    body('meta_description_en').optional().trim(),
    body('meta_description_ar').optional().trim(),
];

export const productUpdateValidator = [
    param('id').custom((value) => mongoose.Types.ObjectId.isValid(value)).withMessage('Invalid product ID'),
    body('category_id').optional().custom((value) => mongoose.Types.ObjectId.isValid(value)),
    body('name_en').optional().trim().notEmpty(),
    body('name_ar').optional().trim().notEmpty(),
    body('slug').optional().trim().notEmpty(),
    body('description_en').optional().trim(),
    body('description_ar').optional().trim(),
    body('short_description_en').optional().trim(),
    body('short_description_ar').optional().trim(),
    body('image').optional().trim(),
    body('images').optional().isArray(),
    body('price').optional().isFloat({ min: 0 }),
    body('sku').optional().trim(),
    body('stock').optional().isInt({ min: 0 }),
    body('is_active').optional().isBoolean(),
    body('is_featured').optional().isBoolean(),
    body('order').optional().isInt(),
    body('meta_title_en').optional().trim(),
    body('meta_title_ar').optional().trim(),
    body('meta_description_en').optional().trim(),
    body('meta_description_ar').optional().trim(),
];
